apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:fq3CSuyaTOIzSvS98Hara2dx/VF2fUyrm1Bucvfs5tUXlUMr,iv:780AgaKnPpLvheFvX/8ljkH6s9mQXHb11WROrhzTTpc=,tag:rCnK+A9SW4xlVrxdVTQXYQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:G4U+parn/cJWtx4M4enypGxbLhhB+jYXW77tC9sYOBIjqZK2cUb41ngEbXD4b0x/z7sE6Pe4Kh0QPvP79j10l0TSu/dDanOEv4vbS1lOrKS9skERPyoIBq0+ZpPPyZ8+9Q3Ky9ANyUb7xteqmm3lbmJHsqWzxGUnPRvs8zFPk+tuPJyxROARs3Tk9VAfR8YgDhSGzi5hcm0OA+GBo9co8THhN/U5eG9OvCfx0a8OHA==,iv:rPpINjIxy9cT3G6eYX8QdpRNaKs3nhoKIqfYphSxmqE=,tag:bibKYaZcbYQgYsmq0DIXDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q3c87pe0mwm8zfzmxgn5pycenfyphv7jsrz4luc0ven0lujg2ysqgxncm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWG43d05LaDI1K3BrWGlI
            UUFMZ1FFZUpHdGJCczNPaHhjYWRsRFFRVHc4CmFUaHdtRE5HODg4d1NvMEo4VHRy
            dTlTQlU2U3hBbWg4RThGU3Y5TzVtMW8KLS0tIGpKMGFEa2xpdHJFNWhLQzBac0Uz
            OUhFR1hhTDVHUXNIVEtsUCtKNnptZEEKBs0FYjjtc/zfO6hexI7yiviaSSLMOcSK
            HxFw44nLjI5ad6hDIdFzteFV2ckr1rJ77yFsFMU2VswgumshJbaYmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T01:39:53Z"
    mac: ENC[AES256_GCM,data:1IZRisK/mTG9NUzNalBp+cKmEeSc31qy0wU7cPBPfxn77A2MqdrV+gttlUoM21Z+tTGywcCovzPgKvD/YdFz/k0KdNl0KCjz4Cyd7I1oTDL0cZvm9YtIqpkU0YRImEH69ktKX1DbWKdsOMk436+aSyWXMtmmdNuKR7Xdjq9Ai7E=,iv:FMTXMi/pnPyMoIkEg2HClChIgPcqVVplcxLA1WaLueU=,tag:hIW4TnL18yP5dwj8Z7xbmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
