apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:lOq6XU8MxHA0uIp0pEw8Q6fzKcfObFvTXKMshiNCgfLlTeShDnpoMA==,iv:CsrajJMwwRg2aB/CuwIEsSJ2m+NL8wBaDjslVJO2gSU=,tag:5O/TFxLRt8YS9efmlPyzcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q3c87pe0mwm8zfzmxgn5pycenfyphv7jsrz4luc0ven0lujg2ysqgxncm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVXV5cTRMcjYwWnVJK2Jh
            SVVFWkVNU2pMeVFkOXBqNy90VXBvMzZ2M2o0Ck5wdVpyOEdDUXlZWVVEZDdLenM0
            OEU4aUNvV1RWMEgwY1IrZmlLcDluWkEKLS0tIFBoNXEzeXlrSmhZRlJPU0ZycGlT
            Nlk0YXdpcHBBQVp0SDhBU3JPVHJMb2sKCTTgfht/VKn0emcc4TewEwaRy/e246xZ
            FO+4D9kZD4xS2pyzY91VBhEtZrSUg5ZiZ16ZIWvJvDon4KTxfDwEsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T05:17:56Z"
    mac: ENC[AES256_GCM,data:sUlawlT7wamu//pnY0u2AgDPHe7PRcODu5JiX4R5VyBZ+nyR16rjMJF2c1YukA7ui6Mr/y8xhTkh5auYnazaRLm4BtOCFcBjW/8Xf2vGClMLmFpVosThbo3Wz7SOvhYKxgyiIZxPCnVqOSVNXET1znYAK0u2RhWDl4dSOTKxabM=,iv:Wy7V4ZCTUo+5tn4RxL0ne6XUsPihgk+5iltf16FBHvU=,tag:b80Ihl3lp3qxM4duPcF9qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
