apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:hIgw80KLGWJJxri0CkgDpCSsjuSmY+S2qfjqA910/PJhVQNViwrgrQ==,iv:r4oCNliVdesrI1FfaCIyHPNfg9cDZJRof5lDfQeB+Ow=,tag:XolK5VZ1GuM1uvJtjiW8Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q3c87pe0mwm8zfzmxgn5pycenfyphv7jsrz4luc0ven0lujg2ysqgxncm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCalhDVUlZZzNBSE9NMjRS
            ckVVNFdWTFRnNllpM0hJZWtDcU9IWDRzam53CkNjVzZabFhvc21QTHlBTCsvdGNy
            aXNDTWNhbUZRYkhXU3E1aUJiSjRROGMKLS0tIGljY3pvRTkxNmg5OExUK1ZGUWNQ
            K3E4aC8xSXczNDJYVG9HUE1oeERsa2sKCsWm21TMHDualUi/ccDGQnmV1lZQoDRu
            wOvLUQjkCaiFOcpbDBGq26bGarZuWE9NqvRqZa+LMpb44IOsRj1+nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T04:24:15Z"
    mac: ENC[AES256_GCM,data:Ke+ukDe2bUMpSE8pPsMYCxqXR8Eo0mYStALADGE+SZFPdQw+7erQfynvNMOWl3tqhhE15kalLQCvT1DhV/b4q4gyhP/dAOhneFRt96WTATD3bzrkOoaMqndGY06J68TsTmCUU536GXIL1oRGWdPfOSUy0smg+X+qFjKDX5vuH/M=,iv:A5e+zG/vBVOsegDQuwzFb9yD4Zh3te6yyj/ALdV8A+I=,tag:xpnd96MBVYo3astw0MV/dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
