apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:xRLe5Q5jJT0450s1Zh1t8LN9H7b7Ix9EAwcwX8M2np0=,iv:OYD2Utrj/iX5SQkmCCPg9Y3H3MPS7pnRX4I3Okk6jsY=,tag:r26Ex6HEB+FlMtZ0qce13w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q3c87pe0mwm8zfzmxgn5pycenfyphv7jsrz4luc0ven0lujg2ysqgxncm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoa0ErZ0tEUTl4dDJReDFR
            QjBBVFo2QVFiTlYwTk9rZksvVlNIRVVqSkFjCkFHZzJFdDhmWXFzQktTcVBCUklO
            a3A2NnJlNHF0bVcxZUtEaWlMQUw0U0UKLS0tIHBWeWJDQXNaeTk5dXZreDF5djBV
            NGh1aFZlc2hQVFpwUUhLRzFGYVhweHMKDKriOG/KSPnBcm0tjgpzAXTzFJLu6v2D
            Tm1RE6Wq3KjnwPeRoRgH3hgBUfP+LGedg9+5/eT1qxdo5Fe1fditZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T05:18:13Z"
    mac: ENC[AES256_GCM,data:W364r2gRmRpA/y6twX+ufXeBdAGevYJ3pMEbOwZgLnFK9j/beEKLnHi0My5PhrOfj7jAfiTcUt/yjKMAwlFB85KCKqTH+dpG9plyHCVbXpWp1YFQ0qYpRbQyprnVO116mg5Y6dNvEFFKwTRp1DwOqtEIveIeGgk4069cXe1aIk4=,iv:C4hILT81eZAPo55qxa/EdGSYKr+tRNtBZNw9L3yvAl4=,tag:k9pGP5CHa0bieUyzKZaFJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
