apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:buDfEKruFLfvgx54OyoXwIW2Dn/6pBunSQnKSYpqgoyKdJjf8k7nzw==,iv:D73Qc3j9DizaO9Hkfufu6q5KAcSOyqatxysBRexpXuA=,tag:/TDCWvK6MQj8r1jr8JPRAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q3c87pe0mwm8zfzmxgn5pycenfyphv7jsrz4luc0ven0lujg2ysqgxncm8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreVNnMVdJR3RiWjN5RkVQ
            SitIK3ROQjk3ekhwazY0UmNGZWNOS0RjM204ClNoaGpoWXZzTURiZUY4S1IzL1Vw
            Nk01KytnRFYrU0k3UGFscjF2WjRLV2cKLS0tIHFjWGYxRjRUdHFtS0REbWJjY3dl
            WDEzQ09lVHFFbWdlUVV4K3phMHMyMlkK2PgifjnAFezwi2zwyXwD4OD1sPe6dTb8
            kJuvyFfDvAS3jkfcnqO/yQy/VEXrcyY47/akIQs/5j2g/gXddWnkaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T04:24:15Z"
    mac: ENC[AES256_GCM,data:ILURLbeOqiYUU8X2gLoLgWYIWlFcpWqcstg5kVOZE6W76RQLccajHWerUOvIyqtGnalTo0h08YFWlzq/GQ7N7d3Jk2dOEF2W2KXKaWgb+BZ0XGJwxKpHPIWr3cj4T1rYumhY/aX9gFiZ0wWzuGm0jMm4uK2rd6OoTmEQEuAvEuQ=,iv:7D1xIxzsJ1JppoEmg+3C7fpatlDPMWXJ/5DryyKpLZ4=,tag:HzS9n9cIsl0pmsrunZuZWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
